### ISSUE TITLE
The SCSS in the source-code folder is old

### ISSUE THREAD

**Issue by jdickan** [labelle/evolution-icons#20]
- need to replace with updated scss

**Comment by jdickan** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;tuhDVTtY&#x2F;852-final-icons-task"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Final Icons task</a>

**Comment by rossathuman** [comment]
Closed as a result of duplication.
